-- Q1
CREATE TABLE DEPT
(
    DEPT_ID NUMBER(7) PRIMARY KEY,
    DEPT_NAME VARCHAR2(20)
);
DESC DEPT;

-- Q2
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (10, 'Accounts');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (20, 'TT');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (30, 'Accounts');
SELECT * FROM DEPT;

-- Q3
CREATE TABLE EMP
(
    ID NUMBER(7) PRIMARY KEY,
    LAST_NAME VARCHAR2(25) NOT NULL,
    FIRST_NAME VARCHAR2(25),
    DEPT_ID NUMBER(7),
    CONSTRAINT FK_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPT(DEPT_ID)
);
INSERT INTO EMP
VALUES (101, 'Sundar', 'Sam', 10);
INSERT INTO EMP
VALUES (101, 'Krishna', 'Ram', 20);
INSERT INTO EMP
VALUES (102, NULL, 'Gopi', 40);
INSERT INTO EMP
VALUES (103, 'Ram', NULL, 20);
SELECT * FROM EMP;